# A dockerized stack for development
version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./import:/opt/osmt/import:rw
    environment:
      - "ENVIRONMENT=${ENVIRONMENT:-dev,apiserver,bucket4j,oauth2-okta}"
      - "BASE_DOMAIN=${BASE_DOMAIN}"
      - "FRONTEND_URL=${FRONTEND_URL}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_URI=${DB_USER}:${DB_PASSWORD}@db:3306"
      - "MIGRATIONS_ENABLED=${MIGRATIONS_ENABLED}"
      - "REINDEX_ELASTICSEARCH=${REINDEX_ELASTICSEARCH}"
      - "ELASTICSEARCH_URI=${ELASTICSEARCH_URI}"
      - "REDIS_URI=${REDIS_URI}"
      - "OAUTH_ISSUER=${OAUTH_ISSUER}"
      - "OAUTH_CLIENTID=${OAUTH_CLIENTID}"
      - "OAUTH_CLIENTSECRET=${OAUTH_CLIENTSECRET}"
      - "OAUTH_AUDIENCE=${OAUTH_AUDIENCE}"
    depends_on:
      - db
      - elasticsearch
      - redis
    ports:
      - "8080:8080"
    networks:
      - osmt

  db:
    image: library/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb3 --collation-server=utf8mb3_unicode_ci
    volumes:
      - osmt_sql_db:/var/lib/mysql:rw
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_HOST=0.0.0.0"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"
    networks:
      - osmt

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "net=host"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - osmt

  redis:
    image: library/redis:6.0.6
    ports:
      - "6379:6379"
    networks:
      - osmt

networks:
  osmt:
    driver: bridge

volumes:
  osmt_sql_db:
  elastic_data:
