// Default values of OSMT Roles
export const OSMT_ADMIN = "ROLE_Osmt_Admin"
export const OSMT_CURATOR = "ROLE_Osmt_Curator"

export const ENABLE_ROLES = true

export const ROLES_AUTHORITY : any  = {
  SKILL_UPDATE : [OSMT_ADMIN, OSMT_CURATOR],
  SKILLS_CREATE : [OSMT_ADMIN, OSMT_CURATOR],
  SKILL_PUBLISH : [OSMT_ADMIN],
  COLLECTION_CREATE : [OSMT_ADMIN, OSMT_CURATOR],
  COLLECTION_PUBLISH : [OSMT_ADMIN],
  COLLECTION_UPDATE : [OSMT_ADMIN, OSMT_CURATOR],
  COLLECTION_SKILLS_UPDATE : [OSMT_ADMIN]
}


