# This workflow will Run API tests using Newman

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out branch
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Maven version
        run: mvn -version
      - name: Run API tests
        run: mvn clean install -DskipTests && mvn verify -Prun-api-tests
        env:
          OAUTH_CLIENTID: "${{secrets.OAUTH_CLIENTID}}"
          OAUTH_CLIENTSECRET: "${{secrets.OAUTH_CLIENTSECRET}}"
          OAUTH_AUDIENCE: "${{secrets.OAUTH_AUDIENCE}}"
          OAUTH_ISSUER: "${{secrets.OAUTH_ISSUER}}"
          OKTA_USERNAME: "${{secrets.OKTA_USERNAME}}"
          OKTA_PASSWORD: "${{secrets.OKTA_PASSWORD}}"
          OKTA_URL: "${{secrets.OKTA_URL}}"
          BASE_URL: "http://localhost:8080"
          APP_START_CHECK_RETRY_LIMIT: 100
