# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Maven version
      run: mvn -version
    - name: Build with Maven
      run: mvn -B package
    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: osmt-artifact
        path: /target
  api-test:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Maven version
        run: mvn -version
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: osmt-artifact
      - name: Build with Maven
        run: mvn verify -pl test -Prun-api-tests
        env:
          OAUTH_CLIENTID: "${{secrets.OAUTH_CLIENTID}}"
          OAUTH_CLIENTSECRET: "${{secrets.OAUTH_CLIENTSECRET}}"
          OAUTH_AUDIENCE: "${{secrets.OAUTH_AUDIENCE}}"
          OAUTH_ISSUER: "${{secrets.OAUTH_ISSUER}}"
          OKTA_USERNAME: "${{secrets.OKTA_USERNAME}}"
          OKTA_PASSWORD: "${{secrets.OKTA_PASSWORD}}"
          OKTA_URL: "${{secrets.OKTA_URL}}"
          BASE_URL: "http://localhost:8080"
          APP_START_CHECK_RETRY_LIMIT: 100
