# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    env:
      BASE_URL: 'http://localhost:8080'
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Maven version
      run: mvn -version
    - name: Build with Maven
      run: mvn -B package
    - name: API testing with Maven
      run: mvn verify -Prun-api-tests \
          oktaUsername=${{secrets.OKTA_USERNAME}} \
          oktaPassword=${{secrets.OKTA_PASSWORD}} \
          oktaUrl=${{secrets.OAUTH_ISSUER}} \
          baseUrl=$BASE_URL
